project_id: 3
api_token: 7d694525301a7b7a443d3d434500d2207637d7a0fd695d7b70be8e16c24c8461f88fcab152c85970
files:
  - source: /src/i18n/locales/en/**/*
    translation: /src/i18n/locales/%two_letters_code%/**/%original_file_name%
  - source: /src/modules/petshop/locales/en/**/*
    translation: /src/modules/petshop/locales/%two_letters_code%/**/%original_file_name%
  - source: /src/modules/account/locales/en/**/*
    translation: /src/modules/account/locales/%two_letters_code%/**/%original_file_name%
preserve_hierarchy: 1
