project_id: "your-project-id"
api_token: "your-api-token"
files:
  - source: /src/i18n/locales/en/**/*
    translation: /src/i18n/locales/%two_letters_code%/**/%original_file_name%
preserve_hierarchy: true 